//! `append` run operation.

use super::persistence_error;
use crate::{AppendContextRequest, AppendContextResult, OperationOutcome, Persistence};

/// The append operation uses the semantic persistence request directly.  Its
/// caller-owned ID and timestamp are intentionally not regenerated by core.
pub type Request = AppendContextRequest;

/// Successful `append` data returned by the persistence boundary.
pub type Result = AppendContextResult;

/// Execute an atomic context append.
///
/// Persistence verifies that the run is active and writes exactly one
/// context record plus its matching history entry without changing control
/// revision.  A terminal-run rejection therefore does not require a separate
/// read and cannot create history as a side effect of this operation.
pub fn execute<P>(request: Request, persistence: &P) -> OperationOutcome<Result>
where
    P: Persistence + ?Sized,
{
    match persistence.append_context(request) {
        Ok(result) => OperationOutcome::completed(result),
        Err(error) => persistence_error(error),
    }
}

/// Execute `append` with the persistence port first.
pub fn execute_with_persistence<P>(persistence: &P, request: Request) -> OperationOutcome<Result>
where
    P: Persistence + ?Sized,
{
    execute(request, persistence)
}
