//! `append` run operation.

use super::{persistence_error, show};
use crate::{
    AppendContextRequest, AppendContextResult, CarryAct, CarryRequest, OperationOutcome,
    Persistence, Timestamp,
};
use serde_json::{json, Value};
use std::collections::{BTreeMap, BTreeSet};

/// The append operation uses the semantic persistence request directly.  Its
/// caller-owned ID and timestamp are intentionally not regenerated by core.
pub type Request = AppendContextRequest;

/// Successful `append` data returned by the persistence boundary.
pub type Result = AppendContextResult;

const CARRY_METADATA_KEY: &str = "loop_engine_carry";

fn carry_rejected<T>(message: impl Into<String>) -> OperationOutcome<T> {
    OperationOutcome::rejected("carry-refused", message)
}

fn changed_inputs(dimensions: &Value) -> BTreeSet<String> {
    dimensions
        .as_object()
        .into_iter()
        .flat_map(|object| object.iter())
        .filter_map(|(name, value)| {
            value
                .get("changed")
                .and_then(Value::as_bool)
                .filter(|changed| *changed)
                .map(|_| name.clone())
        })
        .collect()
}

fn selected_output_linkage_error<T>(message: impl Into<String>) -> OperationOutcome<T> {
    OperationOutcome::rejected("selected-output-linkage-refused", message)
}

fn selected_output_linkage_refusal<P>(
    request: &Request,
    persistence: &P,
) -> Option<OperationOutcome<Result>>
where
    P: Persistence + ?Sized,
{
    let object = request.data.as_object()?;
    let legacy_digest = object
        .get("originating_output_sha256")
        .and_then(Value::as_str);
    let legacy_path = object
        .get("originating_output_path")
        .and_then(Value::as_str);
    if legacy_digest.is_some() || legacy_path.is_some() {
        let (Some(digest), Some(path)) = (legacy_digest, legacy_path) else {
            return Some(selected_output_linkage_error(
                "both originating_output_sha256 and originating_output_path are required",
            ));
        };
        let invocations = match persistence.load_work_slot_invocations(&request.run_id) {
            Ok(invocations) => invocations,
            Err(error) => return Some(persistence_error(error)),
        };
        let matches = invocations
            .iter()
            .flat_map(|invocation| invocation.inner_workers.iter())
            .filter(|worker| {
                worker.selected_attempt.is_some()
                    && worker.selected_output_sha256.as_deref() == Some(digest)
                    && worker.selected_output_path.as_deref() == Some(path)
            })
            .count();
        return (matches != 1).then(|| {
            selected_output_linkage_error(
                "originating output digest/path does not uniquely match an engine-selected attempt",
            )
        });
    }
    let link = object.get("originating_output")?;
    let Some(link) = link.as_object() else {
        return Some(selected_output_linkage_error(
            "`originating_output` must be an object",
        ));
    };
    let string = |name: &str| {
        link.get(name)
            .and_then(Value::as_str)
            .filter(|value| !value.is_empty())
    };
    let Some(invocation_id) = string("invocation_id") else {
        return Some(selected_output_linkage_error(
            "`originating_output.invocation_id` is required",
        ));
    };
    let Some(assignment_id) = string("assignment_id") else {
        return Some(selected_output_linkage_error(
            "`originating_output.assignment_id` is required",
        ));
    };
    let Some(selected_attempt) = link
        .get("selected_attempt")
        .and_then(Value::as_u64)
        .and_then(|value| u32::try_from(value).ok())
    else {
        return Some(selected_output_linkage_error(
            "`originating_output.selected_attempt` must be a non-negative 32-bit integer",
        ));
    };
    let Some(sha256) = string("sha256") else {
        return Some(selected_output_linkage_error(
            "`originating_output.sha256` is required",
        ));
    };
    let Some(path) = string("path") else {
        return Some(selected_output_linkage_error(
            "`originating_output.path` is required",
        ));
    };
    let invocations = match persistence.load_work_slot_invocations(&request.run_id) {
        Ok(invocations) => invocations,
        Err(error) => return Some(persistence_error(error)),
    };
    let Some(invocation) = invocations
        .iter()
        .find(|invocation| invocation.invocation_id.as_str() == invocation_id)
    else {
        return Some(selected_output_linkage_error(format!(
            "originating invocation `{invocation_id}` was not found"
        )));
    };
    let Some(worker) = invocation
        .inner_workers
        .iter()
        .find(|worker| worker.assignment_id == assignment_id)
    else {
        return Some(selected_output_linkage_error(format!(
            "assignment `{assignment_id}` was not found in invocation `{invocation_id}`"
        )));
    };
    (worker.selected_attempt != Some(selected_attempt)
        || worker.selected_output_sha256.as_deref() != Some(sha256)
        || worker.selected_output_path.as_deref() != Some(path))
    .then(|| {
        selected_output_linkage_error(
            "originating output identity does not match the engine-selected attempt",
        )
    })
}

fn current_subjects<P>(
    persistence: &P,
    run_id: &crate::RunId,
    invocations: &[crate::WorkSlotInvocation],
) -> std::result::Result<BTreeMap<crate::WorkSlotId, String>, crate::PersistenceError>
where
    P: Persistence + ?Sized,
{
    let mut subjects = BTreeMap::new();
    for slot_id in invocations
        .iter()
        .map(|item| item.slot_id.clone())
        .collect::<std::collections::BTreeSet<_>>()
    {
        if let Some(subject) = persistence.get_current_slot_subject(run_id, &slot_id)? {
            subjects.insert(slot_id, subject);
        }
    }
    Ok(subjects)
}

fn carry_append<P>(
    request: Request,
    carry: CarryRequest,
    persistence: &P,
) -> OperationOutcome<Result>
where
    P: Persistence + ?Sized,
{
    // Do not use `load_show_data` here: show is the observation that arms a
    // mutation. Carry must inspect the durable report without manufacturing
    // that observation, then let the final append enforce it atomically.
    let run = match persistence.load_authoritative_run(&request.run_id) {
        Ok(run) => run,
        Err(error) => return persistence_error(error),
    };
    let context_records = match persistence.load_context_records(&request.run_id) {
        Ok(context) => context,
        Err(error) => return persistence_error(error),
    };
    let checked_evaluations = match persistence.load_checked_evaluations(&request.run_id) {
        Ok(evaluations) => evaluations,
        Err(error) => return persistence_error(error),
    };
    let data = crate::ShowData {
        run,
        context: context_records,
        checked_evaluations,
    };
    let context = data.context.clone();
    let source = if carry.source_record_id.as_str().is_empty() {
        None
    } else {
        match context
            .iter()
            .find(|record| record.id == carry.source_record_id)
        {
            Some(record) => Some(record),
            None => {
                return carry_rejected(format!(
                    "source context record `{}` was not found; carry reads the originating record",
                    carry.source_record_id
                ))
            }
        }
    };
    let source_data = source
        .map(|record| record.data.clone())
        .unwrap_or_else(|| json!({}));
    let Some(source_object) = source_data.as_object() else {
        return carry_rejected(format!(
            "source context record `{}` is not an object and cannot carry provenance",
            carry.source_record_id
        ));
    };

    let invocations = match persistence.load_work_slot_invocations(&request.run_id) {
        Ok(invocations) => invocations,
        Err(error) => return persistence_error(error),
    };
    let Some(invocation) = invocations
        .iter()
        .find(|invocation| invocation.invocation_id == carry.invocation_id)
    else {
        return carry_rejected(format!(
            "originating invocation `{}` was not found",
            carry.invocation_id
        ));
    };
    let Some(worker) = invocation
        .inner_workers
        .iter()
        .find(|worker| worker.assignment_id == carry.assignment_id)
    else {
        return carry_rejected(format!(
            "assignment `{}` was not found in invocation `{}`",
            carry.assignment_id, carry.invocation_id
        ));
    };
    let Some(originating_output_sha256) = worker.selected_output_sha256.clone() else {
        return carry_rejected(format!(
            "assignment `{}` has no selected originating output; a coverage gap cannot be carried",
            carry.assignment_id
        ));
    };
    let originating_output_path = worker.selected_output_path.clone();
    let originating_attempt = worker.selected_attempt;

    let subjects = match current_subjects(persistence, &request.run_id, &invocations) {
        Ok(subjects) => subjects,
        Err(error) => return persistence_error(error),
    };
    let report = match show::project_with_invocations_and_subjects(
        data,
        &invocations,
        Timestamp::from_unix_millis(0),
        |_| false,
        &subjects,
    ) {
        Ok(projection) => projection
            .work_slot_invocations
            .into_iter()
            .find(|view| view.invocation_id == carry.invocation_id)
            .map(|view| view.change_report),
        Err(error) => {
            return OperationOutcome::error("change-report-unavailable", error.to_string())
        }
    };
    let Some(report) = report else {
        return carry_rejected("the change report of record has no originating invocation");
    };
    let dimensions = report
        .plan_task_results
        .iter()
        .find(|result| result.assignment_id == carry.assignment_id)
        .map(|result| result.dimensions.clone())
        .or_else(|| {
            report
                .assignments
                .iter()
                .find(|judgment| judgment.assignment_id == carry.assignment_id)
                .map(|_| report.dimensions.clone())
        });
    let Some(dimensions) = dimensions else {
        return carry_rejected(format!(
            "assignment `{}` has no recorded change report",
            carry.assignment_id
        ));
    };
    let changed = changed_inputs(&dimensions);
    let named: BTreeSet<String> = carry.overridden_inputs.iter().cloned().collect();
    match carry.act {
        CarryAct::Unchanged if !changed.is_empty() => {
            return carry_rejected(format!(
                "unchanged-carry refused: the change report of record shows changed inputs: {}",
                changed.into_iter().collect::<Vec<_>>().join(", ")
            ));
        }
        CarryAct::Unchanged if !named.is_empty() => {
            return carry_rejected("unchanged-carry does not accept overridden inputs");
        }
        CarryAct::Override => {
            let missing: Vec<_> = changed.difference(&named).cloned().collect();
            if !missing.is_empty() {
                return carry_rejected(format!(
                    "override-carry must name every changed input in the change report of record: {}",
                    missing.join(", ")
                ));
            }
        }
        _ => {}
    }

    let mut carried_data = Value::Object(source_object.clone());
    carried_data.as_object_mut().expect("object above").insert(
        CARRY_METADATA_KEY.to_owned(),
        json!({
            "act": carry.act.as_str(),
            "source_record_id": source.map(|record| record.id.clone()),
            "invocation_id": carry.invocation_id,
            "assignment_id": carry.assignment_id,
            "attesting_driver": carry.attesting_driver,
            "overridden_inputs": carry.overridden_inputs,
            "attested_dimensions": dimensions,
            "originating_output_sha256": originating_output_sha256,
            "originating_output_path": originating_output_path,
            "originating_attempt": originating_attempt,
        }),
    );

    let derived = AppendContextRequest {
        run_id: request.run_id,
        record_id: request.record_id,
        kind: source
            .map(|record| record.kind.clone())
            .unwrap_or_else(|| "loop-engine-carry".to_owned()),
        data: carried_data,
        created_at: request.created_at,
        carry: None,
    };
    match persistence.append_context(derived) {
        Ok(result) => OperationOutcome::completed(result),
        Err(error) => persistence_error(error),
    }
}

/// Execute an atomic context append, or one of the two explicit carry acts.
///
/// The carry path computes the durable show report before writing anything;
/// the caller cannot supply a cleanliness assertion or replacement evidence.
pub fn execute<P>(request: Request, persistence: &P) -> OperationOutcome<Result>
where
    P: Persistence + ?Sized,
{
    if let Some(carry) = request.carry.clone() {
        return carry_append(request, carry, persistence);
    }
    if let Some(outcome) = selected_output_linkage_refusal(&request, persistence) {
        return outcome;
    }
    match persistence.append_context(request) {
        Ok(result) => OperationOutcome::completed(result),
        Err(error) => persistence_error(error),
    }
}

/// Execute `append` with the persistence port first.
pub fn execute_with_persistence<P>(persistence: &P, request: Request) -> OperationOutcome<Result>
where
    P: Persistence + ?Sized,
{
    execute(request, persistence)
}
