//! `append` run operation.

use super::persistence_error;
use crate::{
    AppendContextRequest, AppendContextResult, EngineOrigin, EvidenceApplicability,
    OperationOutcome, OriginReference, Persistence, PersistenceError, ENGINE_ORIGIN_KEY,
    EVIDENCE_APPLICABILITY_KIND, ORIGIN_KEY,
};
use serde_json::{Map, Value};
use std::path::{Component, Path};

/// The append operation uses the semantic persistence request directly. Its
/// caller-owned ID and timestamp are intentionally not regenerated by core.
pub type Request = AppendContextRequest;

/// Successful `append` data returned by the persistence boundary.
pub type Result = AppendContextResult;

const LEGACY_ORIGIN_KEYS: &[&str] = &[
    ENGINE_ORIGIN_KEY,
    "loop_engine_carry",
    "originating_output",
    "originating_output_sha256",
    "originating_output_path",
    "overridden_inputs",
    "attested_dimensions",
    "selected_attempt",
    "selected_output_sha256",
    "selected_output_path",
    "capture_dir",
    "command",
    "args",
    "binding",
];

enum PreparationError {
    Rejected { code: &'static str, message: String },
    Persistence(PersistenceError),
}

impl PreparationError {
    fn rejected(code: &'static str, message: impl Into<String>) -> Self {
        Self::Rejected {
            code,
            message: message.into(),
        }
    }

    fn origin(message: impl Into<String>) -> Self {
        Self::rejected("selected-output-linkage-refused", message)
    }

    fn applicability(message: impl Into<String>) -> Self {
        Self::rejected("evidence-applicability-refused", message)
    }

    fn legacy_carry(message: impl Into<String>) -> Self {
        Self::rejected("carry-refused", message)
    }
}

fn legacy_origin_key(data: &Map<String, Value>) -> Option<&'static str> {
    LEGACY_ORIGIN_KEYS
        .iter()
        .copied()
        .find(|key| data.contains_key(*key))
}

fn parse_origin(data: &Map<String, Value>) -> std::result::Result<Option<OriginReference>, String> {
    let Some(value) = data.get(ORIGIN_KEY) else {
        return Ok(None);
    };
    serde_json::from_value(value.clone())
        .map(Some)
        .map_err(|error| format!("`{ORIGIN_KEY}` is not a valid stable origin reference: {error}"))
}

fn require_nonempty(value: &str, field: &str) -> std::result::Result<(), String> {
    if value.trim().is_empty() {
        Err(format!("`{field}` must be a non-empty string"))
    } else {
        Ok(())
    }
}

fn validate_context_origin<P>(
    request: &Request,
    origin: &OriginReference,
    persistence: &P,
) -> std::result::Result<(), PreparationError>
where
    P: Persistence + ?Sized,
{
    if origin.kind != "context-record" {
        return Err(PreparationError::applicability(format!(
            "evidence applicability origin kind must be `context-record`, got `{}`",
            origin.kind
        )));
    }
    if let Some(assignment_id) = origin.assignment_id.as_deref() {
        return Err(PreparationError::applicability(format!(
            "context-record origin must not carry assignment_id `{assignment_id}`"
        )));
    }
    if let Err(error) = require_nonempty(&origin.id, "origin.id") {
        return Err(PreparationError::applicability(error));
    }
    let records = match persistence.load_context_records(&request.run_id) {
        Ok(records) => records,
        Err(error) => return Err(PreparationError::Persistence(error)),
    };
    if records.iter().any(|record| record.id.as_str() == origin.id) {
        Ok(())
    } else {
        Err(PreparationError::applicability(format!(
            "context record `{}` was not found on run `{}`",
            origin.id, request.run_id
        )))
    }
}

fn path_is_contained(capture_dir: &str, selected_path: &str, allow_relative: bool) -> bool {
    if capture_dir.trim().is_empty() || selected_path.trim().is_empty() {
        return false;
    }

    let selected = Path::new(selected_path);
    if selected.components().any(|component| {
        matches!(
            component,
            Component::ParentDir | Component::CurDir | Component::Prefix(_)
        )
    }) {
        return false;
    }
    let capture = Path::new(capture_dir);
    if !capture.is_absolute() {
        return false;
    }
    if selected.is_absolute() {
        selected
            .strip_prefix(capture)
            .map(|relative| !relative.as_os_str().is_empty())
            .unwrap_or(false)
    } else {
        allow_relative
            && selected
                .components()
                .all(|component| matches!(component, Component::Normal(_)))
            && !selected.as_os_str().is_empty()
    }
}

fn validate_recovered_worker(
    request: &Request,
    invocation: &crate::WorkSlotInvocation,
    worker: &crate::InnerWorker,
) -> std::result::Result<Value, PreparationError> {
    let source = worker.recovery_source.as_ref().ok_or_else(|| {
        PreparationError::origin("recovered selected output is missing recovery_source")
    })?;
    let origin = source.get("origin").ok_or_else(|| {
        PreparationError::origin("recovered selected output is missing its original source")
    })?;
    if source.get("protocol").and_then(Value::as_str) != Some("fan-out-selected-source-v1")
        || source.get("execution").and_then(Value::as_str) != Some("reused")
        || !matches!(
            source.get("source_class").and_then(Value::as_str),
            Some("original-raw" | "eligible-derived")
        )
        || source.get("selected_output_sha256").and_then(Value::as_str)
            != worker.selected_output_sha256.as_deref()
        || source.get("selected_output_path").and_then(Value::as_str)
            != worker.selected_output_path.as_deref()
        || origin.get("run_id").and_then(Value::as_str) != Some(request.run_id.as_str())
        || origin.get("slot_id").and_then(Value::as_str) != Some(invocation.slot_id.as_str())
        || origin.get("assignment_id").and_then(Value::as_str)
            != Some(worker.assignment_id.as_str())
        || origin
            .get("invocation_id")
            .and_then(Value::as_str)
            .is_none_or(str::is_empty)
        || origin
            .get("raw_attempt")
            .and_then(Value::as_u64)
            .is_none_or(|attempt| attempt == 0)
        || origin
            .get("raw_stdout_sha256")
            .and_then(Value::as_str)
            .is_none_or(|digest| digest.trim().is_empty())
        || origin
            .get("raw_stdout_path")
            .and_then(Value::as_str)
            .is_none_or(str::is_empty)
        || origin
            .get("capture_dir")
            .and_then(Value::as_str)
            .is_none_or(str::is_empty)
    {
        return Err(PreparationError::origin(
            "recovered selected output identity does not match its engine assignment",
        ));
    }
    Ok(source.clone())
}

fn resolve_selected_output<P>(
    request: &Request,
    origin: &OriginReference,
    persistence: &P,
) -> std::result::Result<EngineOrigin, PreparationError>
where
    P: Persistence + ?Sized,
{
    if origin.kind != "selected-assignment-output" {
        return Err(PreparationError::origin(format!(
            "unsupported origin kind `{}`; expected `selected-assignment-output` or `context-record`",
            origin.kind
        )));
    }
    if let Err(error) = require_nonempty(&origin.id, "origin.id") {
        return Err(PreparationError::origin(error));
    }
    let Some(assignment_id) = origin.assignment_id.as_deref() else {
        return Err(PreparationError::origin(
            "selected-assignment-output origin requires assignment_id",
        ));
    };
    if let Err(error) = require_nonempty(assignment_id, "origin.assignment_id") {
        return Err(PreparationError::origin(error));
    }

    let invocations = match persistence.load_work_slot_invocations(&request.run_id) {
        Ok(invocations) => invocations,
        Err(error) => return Err(PreparationError::Persistence(error)),
    };
    let matching_invocations = invocations
        .iter()
        .filter(|invocation| invocation.invocation_id.as_str() == origin.id)
        .collect::<Vec<_>>();
    let Some(invocation) = matching_invocations.first().copied() else {
        return Err(PreparationError::origin(format!(
            "invocation `{}` was not found on run `{}`",
            origin.id, request.run_id
        )));
    };
    if matching_invocations.len() != 1 {
        return Err(PreparationError::origin(format!(
            "invocation `{}` is ambiguous on run `{}`",
            origin.id, request.run_id
        )));
    }

    let workers = invocation
        .inner_workers
        .iter()
        .filter(|worker| worker.assignment_id == assignment_id)
        .collect::<Vec<_>>();
    let Some(worker) = workers.first().copied() else {
        return Err(PreparationError::origin(format!(
            "assignment `{assignment_id}` was not found in invocation `{}`",
            origin.id
        )));
    };
    if workers.len() != 1 {
        return Err(PreparationError::origin(format!(
            "assignment `{assignment_id}` is ambiguous in invocation `{}`",
            origin.id
        )));
    }

    let recovered_source = if worker.selected_attempt.is_none() {
        Some(validate_recovered_worker(request, invocation, worker)?)
    } else if worker.recovery_source.is_some() {
        return Err(PreparationError::origin(
            "recovered selected output must not claim a new selected attempt",
        ));
    } else {
        None
    };
    let selected_attempt = worker.selected_attempt;
    let Some(selected_output_sha256) = worker.selected_output_sha256.as_deref() else {
        return Err(PreparationError::origin(format!(
            "assignment `{assignment_id}` in invocation `{}` has no selected output digest",
            origin.id
        )));
    };
    let Some(selected_output_path) = worker.selected_output_path.as_deref() else {
        return Err(PreparationError::origin(format!(
            "assignment `{assignment_id}` in invocation `{}` has no selected output path",
            origin.id
        )));
    };
    if selected_output_sha256.trim().is_empty() || selected_output_path.trim().is_empty() {
        return Err(PreparationError::origin(format!(
            "assignment `{assignment_id}` in invocation `{}` has an incomplete selected output",
            origin.id
        )));
    }
    if !path_is_contained(&invocation.capture_dir, selected_output_path, true) {
        return Err(PreparationError::origin(format!(
            "selected output path for assignment `{assignment_id}` is not contained by invocation capture_dir"
        )));
    }

    let mut resolved = EngineOrigin::new(
        invocation.invocation_id.clone(),
        worker.assignment_id.clone(),
        selected_attempt,
        selected_output_sha256,
        selected_output_path,
        invocation.capture_dir.clone(),
        worker.command.clone(),
        worker.args.clone(),
        invocation.binding.clone(),
    );
    resolved.slot_id = Some(invocation.slot_id.as_str().to_owned());
    resolved.recovery_source = recovered_source;
    Ok(resolved)
}

fn prepare_data<P>(
    request: &Request,
    persistence: &P,
) -> std::result::Result<Value, PreparationError>
where
    P: Persistence + ?Sized,
{
    if request.carry.is_some() {
        return Err(PreparationError::legacy_carry(
            "legacy carry requests are no longer accepted; use an evidence-applicability record",
        ));
    }
    if matches!(request.kind.as_str(), "unchanged-carry" | "override-carry") {
        return Err(PreparationError::legacy_carry(format!(
            "context kind `{}` is retired; use `{EVIDENCE_APPLICABILITY_KIND}`",
            request.kind
        )));
    }

    let Some(object) = request.data.as_object() else {
        return Ok(request.data.clone());
    };
    if let Some(key) = legacy_origin_key(object) {
        return Err(PreparationError::origin(format!(
            "legacy or engine-owned origin field `{key}` cannot be supplied by the caller"
        )));
    }

    if request.kind == EVIDENCE_APPLICABILITY_KIND {
        let applicability = serde_json::from_value::<EvidenceApplicability>(request.data.clone())
            .map_err(|error| {
                PreparationError::applicability(format!(
                    "`{EVIDENCE_APPLICABILITY_KIND}` data must contain only origin, target, attesting_driver, and reason: {error}"
                ))
            })?;
        if applicability.target.is_null() {
            return Err(PreparationError::applicability(
                "evidence applicability target must be present and non-null",
            ));
        }
        if applicability.attesting_driver.is_null() {
            return Err(PreparationError::applicability(
                "evidence applicability attesting_driver must be present and non-null",
            ));
        }
        if applicability.reason.trim().is_empty() {
            return Err(PreparationError::applicability(
                "evidence applicability reason must be a non-empty string",
            ));
        }
        validate_context_origin(request, &applicability.origin, persistence)?;
        return Ok(request.data.clone());
    }

    let Some(origin) = parse_origin(object).map_err(PreparationError::origin)? else {
        return Ok(request.data.clone());
    };
    match origin.kind.as_str() {
        "context-record" => {
            validate_context_origin(request, &origin, persistence)?;
            Ok(request.data.clone())
        }
        "selected-assignment-output" => {
            let resolved = resolve_selected_output(request, &origin, persistence)?;
            let mut enriched = object.clone();
            enriched.insert(
                ENGINE_ORIGIN_KEY.to_owned(),
                serde_json::to_value(resolved).expect("engine origin is serializable"),
            );
            Ok(Value::Object(enriched))
        }
        _ => Err(PreparationError::origin(format!(
            "unsupported origin kind `{}`; expected `selected-assignment-output` or `context-record`",
            origin.kind
        ))),
    }
}

/// Execute an atomic context append.
///
/// New stable references are resolved before the persistence mutation. The
/// persistence adapter still owns observation, lifecycle, ID, and atomicity
/// checks. Legacy carry requests remain decodable but are rejected here.
pub fn execute<P>(request: Request, persistence: &P) -> OperationOutcome<Result>
where
    P: Persistence + ?Sized,
{
    let data = match prepare_data(&request, persistence) {
        Ok(data) => data,
        Err(PreparationError::Rejected { code, message }) => {
            return OperationOutcome::rejected(code, message)
        }
        Err(PreparationError::Persistence(error)) => return persistence_error(error),
    };
    let request = AppendContextRequest { data, ..request };
    match persistence.append_context(request) {
        Ok(result) => OperationOutcome::completed(result),
        Err(error) => persistence_error(error),
    }
}

/// Execute `append` with the persistence port first.
pub fn execute_with_persistence<P>(persistence: &P, request: Request) -> OperationOutcome<Result>
where
    P: Persistence + ?Sized,
{
    execute(request, persistence)
}
