//! Fixture/canary coverage for the T030 dependency policy gate.
//!
//! Canaries are encoded in-process with temporary trees (no separate fixture
//! directory) so unauthorized paths stay untouched.

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;
use std::process::Command;

use tempfile::tempdir;

fn write_minimal_workspace(root: &Path, deny_toml: &str, lock_text: &str) {
    fs::write(root.join("deny.toml"), deny_toml).expect("write deny.toml");
    fs::write(root.join("Cargo.lock"), lock_text).expect("write Cargo.lock");
    fs::write(
        root.join("Cargo.toml"),
        r#"[workspace]
members = ["crate-a"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
"#,
    )
    .expect("write workspace Cargo.toml");
    let crate_dir = root.join("crate-a");
    fs::create_dir_all(crate_dir.join("src")).expect("mkdir crate-a");
    fs::write(
        crate_dir.join("Cargo.toml"),
        r#"[package]
name = "crate-a"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
"#,
    )
    .expect("write crate Cargo.toml");
    fs::write(crate_dir.join("src/lib.rs"), "//! canary crate\n").expect("write lib.rs");
}

fn valid_policy_toml() -> String {
    r#"
[advisories]
yanked = "deny"
unmaintained = "workspace"
ignore = []

[licenses]
confidence-threshold = 0.8
unused-allowed-license = "allow"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "0BSD",
    "Zlib",
    "Unlicense",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
]
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
"#
    .to_string()
}

fn empty_lockfile() -> String {
    "# This file is automatically @generated by Cargo.\nversion = 4\n".to_string()
}

#[test]
fn dependencies_command_is_registered() {
    let output = Command::new(env!("CARGO_BIN_EXE_xtask"))
        .args(["help"])
        .output()
        .expect("xtask help should execute");
    assert!(output.status.success(), "help should succeed");
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(
        stdout.contains("dependencies"),
        "help should list dependencies command: {stdout}"
    );
}

#[test]
fn dependencies_command_passes_for_current_repository() {
    let status = Command::new(env!("CARGO_BIN_EXE_xtask"))
        .arg("dependencies")
        .status()
        .expect("xtask binary should execute");
    assert!(
        status.success(),
        "dependencies command should pass for the current repository"
    );
}

#[test]
fn policy_shape_rejects_missing_required_license() {
    let mut policy = xtask::dependencies::parse_deny_toml(&valid_policy_toml())
        .expect("valid policy should parse");
    policy.allowed_licenses.remove("Unicode-3.0");
    let error = xtask::dependencies::validate_policy_shape(&policy)
        .expect_err("missing Unicode-3.0 must fail policy shape");
    assert!(
        error.to_string().contains("Unicode-3.0"),
        "unexpected error: {error:#}"
    );
}

#[test]
fn policy_shape_rejects_unknown_git_warn() {
    let mut policy = xtask::dependencies::parse_deny_toml(&valid_policy_toml())
        .expect("valid policy should parse");
    policy.unknown_git = xtask::dependencies::LintLevel::Warn;
    let error = xtask::dependencies::validate_policy_shape(&policy)
        .expect_err("unknown-git warn must fail policy shape");
    assert!(
        error.to_string().contains("unknown-git"),
        "unexpected error: {error:#}"
    );
}

#[test]
fn lockfile_git_source_canary_fails() {
    let policy = xtask::dependencies::parse_deny_toml(&valid_policy_toml())
        .expect("valid policy should parse");
    xtask::dependencies::validate_policy_shape(&policy).expect("shape ok");

    let lock = r#"
[[package]]
name = "evil"
version = "0.1.0"
source = "git+https://example.com/evil.git?rev=deadbeef"
"#;
    let error = xtask::dependencies::check_lockfile_sources(lock, &policy)
        .expect_err("git source canary must fail");
    assert!(
        error.to_string().contains("disallowed git source"),
        "unexpected error: {error:#}"
    );
}

#[test]
fn lockfile_unknown_registry_canary_fails() {
    let policy = xtask::dependencies::parse_deny_toml(&valid_policy_toml())
        .expect("valid policy should parse");
    let lock = r#"
[[package]]
name = "evil"
version = "0.1.0"
source = "registry+https://example.com/private-index"
"#;
    let error = xtask::dependencies::check_lockfile_sources(lock, &policy)
        .expect_err("unknown registry canary must fail");
    assert!(
        error.to_string().contains("disallowed registry"),
        "unexpected error: {error:#}"
    );
}

#[test]
fn gpl_only_license_canary_fails() {
    let allowed: BTreeSet<String> = ["MIT", "Apache-2.0"]
        .into_iter()
        .map(str::to_string)
        .collect();
    assert!(
        !xtask::dependencies::license_expression_allowed("GPL-3.0-only", &allowed),
        "GPL-only must conflict with dual MIT/Apache-2.0 allowlist"
    );
}

#[test]
fn missing_deny_toml_canary_fails() {
    let dir = tempdir().expect("tempdir");
    fs::write(dir.path().join("Cargo.lock"), empty_lockfile()).expect("lock");
    fs::write(
        dir.path().join("Cargo.toml"),
        "[workspace]\nmembers = []\nresolver = \"2\"\n",
    )
    .expect("manifest");
    let error = xtask::dependencies::run(Some(dir.path())).expect_err("missing deny.toml");
    assert!(
        error.to_string().contains("deny.toml"),
        "unexpected error: {error:#}"
    );
}

#[test]
fn missing_lockfile_canary_fails() {
    let dir = tempdir().expect("tempdir");
    fs::write(dir.path().join("deny.toml"), valid_policy_toml()).expect("deny");
    fs::write(
        dir.path().join("Cargo.toml"),
        "[workspace]\nmembers = []\nresolver = \"2\"\n",
    )
    .expect("manifest");
    let error = xtask::dependencies::run(Some(dir.path())).expect_err("missing lockfile");
    assert!(
        error.to_string().contains("Cargo.lock"),
        "unexpected error: {error:#}"
    );
}

#[test]
fn valid_temp_workspace_passes_selected_equivalent() {
    let dir = tempdir().expect("tempdir");
    let lock = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "crate-a"
version = "0.1.0"
"#;
    write_minimal_workspace(dir.path(), &valid_policy_toml(), lock);
    xtask::dependencies::run(Some(dir.path()))
        .expect("valid temporary workspace should satisfy dependency policy");
}

#[test]
fn checkpoint_schema_declares_empty_runtime_surface_for_c1() {
    let schema_path =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../quality/evidence/v1/checkpoint.schema.json");
    let text = fs::read_to_string(&schema_path).expect("checkpoint schema must exist");
    let value: serde_json::Value =
        serde_json::from_str(&text).expect("checkpoint schema must be JSON");
    assert_eq!(value["title"], "Checkpoint evidence v1");
    assert_eq!(value["properties"]["schema_version"]["const"], 1);
    let checkpoint_enum = value["properties"]["checkpoint_id"]["enum"]
        .as_array()
        .expect("checkpoint_id enum");
    assert!(
        checkpoint_enum.iter().any(|v| v == "C1"),
        "schema must include C1"
    );
    let required = value["required"].as_array().expect("required");
    for key in [
        "schema_version",
        "checkpoint_id",
        "application_operations",
        "gates",
        "status",
    ] {
        assert!(
            required.iter().any(|v| v == key),
            "missing required key {key}"
        );
    }
    let then_ops = &value["allOf"][0]["then"]["properties"]["application_operations"];
    assert_eq!(then_ops["maxItems"], 0);
}
#[test]
fn cargo_deny_version_is_pinned_for_publication_gate() {
    assert_eq!(xtask::dependencies::CARGO_DENY_VERSION, "0.20.2");
}
