#!/usr/bin/env python3
"""Prove cargo-dist's generated release dependency graph fails closed.

cargo-dist 0.32 renders host's reusable-job results with ``success || skipped``
conditions. Its supported custom-job hooks do not expose a custom ``if`` or
``needs`` expression. This repository therefore puts every proof hook in
``global-artifacts-jobs`` and keeps those generated jobs unconditional: after
successful publishing plan/local matrix jobs, each hook must execute. The
assertion below proves that graph, rather than trusting skipped as success.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Dict, NoReturn, Set

ROOT = Path(__file__).resolve().parents[1]
CARGO_TOML = ROOT / "Cargo.toml"
RELEASE_WORKFLOW = ROOT / ".github/workflows/release.yml"
ARCHIVE_SMOKE_WORKFLOW = ROOT / ".github/workflows/archive-smoke.yml"
REQUIRED_JOBS = {
    "build-local-artifacts",
    "build-global-artifacts",
    "custom-preflight",
    "custom-archive-smoke",
    "host",
}
REQUIRED_GATES = {
    "build-local-artifacts",
    "build-global-artifacts",
    "custom-preflight",
    "custom-archive-smoke",
}


def fail(message: str) -> NoReturn:
    raise SystemExit(f"release gate assertion failed: {message}")


def job_blocks(workflow: str) -> Dict[str, str]:
    try:
        jobs = workflow.split("\njobs:\n", 1)[1]
    except IndexError:
        fail("generated workflow has no jobs section")
    matches = list(re.finditer(r"^  ([A-Za-z0-9_-]+):\n", jobs, re.MULTILINE))
    if not matches:
        fail("generated workflow has no jobs")
    blocks: Dict[str, str] = {}
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(jobs)
        blocks[match.group(1)] = jobs[match.start() : end]
    return blocks


def needs(block: str) -> Set[str]:
    match = re.search(r"^    needs:\n((?:^      - [^\n]+\n)+)", block, re.MULTILINE)
    if not match:
        return set()
    return {line.strip()[2:].strip() for line in match.group(1).splitlines()}


def has_job_if(block: str) -> bool:
    return re.search(r"^    if:", block, re.MULTILINE) is not None


def host_gate_condition(block: str, job: str) -> bool:
    return (
        f"needs.{job}.result == 'skipped'" in block
        and f"needs.{job}.result == 'success'" in block
    )


def graph_allows_publish(statuses: Dict[str, str]) -> bool:
    """Evaluate only statuses reachable through generated cargo-dist graph."""
    if statuses.get("plan") != "success" or statuses.get("publishing") != "true":
        return False

    # Publishing plan has a non-null matrix, so built-in local matrix `if`
    # evaluates true. A skipped matrix is not reachable in this path.
    if statuses.get("build-local-artifacts") != "success":
        return False

    # Global artifact and both global hooks have no generated `if`; with local
    # success they execute. Failure or skip cannot satisfy publication.
    return all(
        statuses.get(job) == "success"
        for job in ("build-global-artifacts", "custom-preflight", "custom-archive-smoke")
    )


def assert_negative(statuses: Dict[str, str], label: str) -> None:
    if graph_allows_publish(statuses):
        fail(f"{label} status was accepted as publishable: {statuses}")


def main() -> int:
    try:
        cargo = CARGO_TOML.read_text(encoding="utf-8")
        workflow = RELEASE_WORKFLOW.read_text(encoding="utf-8")
        archive_smoke = ARCHIVE_SMOKE_WORKFLOW.read_text(encoding="utf-8")
    except OSError as error:
        fail(f"could not read generated release inputs: {error}")

    if 'cargo-dist-version = "0.32.0"' not in cargo:
        fail("Cargo.toml must pin supported cargo-dist 0.32.0")
    if 'global-artifacts-jobs = ["./preflight", "./archive-smoke"]' not in cargo:
        fail("both proof hooks must be cargo-dist global-artifacts jobs")
    if "plan-jobs" in cargo:
        fail("preflight must not be a plan job: plan hooks gate local builds and create skip cascades")
    if not workflow.startswith("# This file was autogenerated by dist:"):
        fail("release.yml lost cargo-dist generated ownership")
    if "  workflow_dispatch:" not in workflow or re.search(r"^  push:", workflow, re.MULTILINE):
        fail("release workflow must be dispatch-only, without tag-push trigger")
    if 'python3 "$GITHUB_WORKSPACE/scripts/software-change-journey.py"' not in archive_smoke:
        fail("archive smoke must invoke software-change runner through absolute GITHUB_WORKSPACE path")
    if "version=2.14.0" not in archive_smoke or "github.com/dagu-org/dagu/releases/download/v${version}/" not in archive_smoke:
        fail("archive smoke must install operator-provided dagu 2.14.0")
    if "echo \"$bin\" >> \"$GITHUB_PATH\"" not in archive_smoke:
        fail("archive smoke must put dagu on PATH")
    if "$RUNNER_TEMP/dagu-bin" not in archive_smoke:
        fail("archive smoke must install dagu into RUNNER_TEMP, not dist artifacts")
    if "continue-on-error" in archive_smoke:
        fail("archive smoke must not skip a missing dagu")
    dagu_at = archive_smoke.find("Install operator-provided dagu")
    journey_at = archive_smoke.find('python3 "$GITHUB_WORKSPACE/scripts/software-change-journey.py"')
    if dagu_at < 0 or journey_at < 0 or dagu_at > journey_at:
        fail("archive smoke must install dagu onto PATH before journeys")
    if "dagu_${version}_darwin_arm64.tar.gz" not in archive_smoke or "dagu_${version}_linux_amd64.tar.gz" not in archive_smoke:
        fail("archive smoke must install platform dagu archives for macos-arm64 and linux-amd64")
    if 'python3 "$GITHUB_WORKSPACE/scripts/policy-document-journey.py"' not in archive_smoke:
        fail("archive smoke must invoke policy-document runner through absolute GITHUB_WORKSPACE path")
    if 'python3 "$GITHUB_WORKSPACE/scripts/research-journey.py"' not in archive_smoke:
        fail("archive smoke must invoke research runner through absolute GITHUB_WORKSPACE path")
    if 'for app in loop-cli software-change-provider policy-document-provider research-provider' not in archive_smoke:
        fail("archive smoke must extract all four release applications")
    if '"$policy_provider" data-dump "$policy_data_root"' not in archive_smoke:
        fail("archive smoke must materialize policy-document profiles from packaged binary")
    if 'for mode in draft audit' not in archive_smoke:
        fail("archive smoke must exercise both policy-document modes")
    if 'research_data_root="$RUNNER_TEMP/research-data-$target"' not in archive_smoke:
        fail("archive smoke must isolate a unique empty research dump root")
    if '--data-root "$research_data_root"' not in archive_smoke:
        fail("archive smoke must pass the isolated research dump root to the packaged journey")
    if '-name research -perm -u+x' not in archive_smoke:
        fail("archive smoke must locate the packaged research executable")
    if 'cd "$smoke_cwd"' not in archive_smoke:
        fail("archive smoke must change into its isolated temporary cwd")
    if 'test "$(pwd -P)" != "$checkout_root"' not in archive_smoke:
        fail("archive smoke lost outside-checkout cwd assertion")
    if 'test -z "$(ls -A "$smoke_cwd")"' not in archive_smoke:
        fail("archive smoke lost empty-cwd assertion")
    for name, reusable in (("preflight", ROOT / ".github/workflows/preflight.yml"),
                           ("archive smoke", ARCHIVE_SMOKE_WORKFLOW)):
        try:
            reusable_text = reusable.read_text(encoding="utf-8")
        except OSError as error:
            fail(f"could not read {name} workflow: {error}")
        if re.search(r"^    if:", reusable_text, re.MULTILINE):
            fail(f"{name} reusable workflow added a skippable job")

    blocks = job_blocks(workflow)
    missing = REQUIRED_JOBS.difference(blocks)
    if missing:
        fail(f"generated release workflow missing jobs: {sorted(missing)}")

    expected_needs = {
        "build-local-artifacts": {"plan"},
        "build-global-artifacts": {"plan", "build-local-artifacts"},
        "custom-preflight": {"plan", "build-local-artifacts"},
        "custom-archive-smoke": {"plan", "build-local-artifacts"},
    }
    for job, required in expected_needs.items():
        actual = needs(blocks[job])
        if actual != required:
            fail(f"{job} needs exactly {sorted(required)}, generated needs are {sorted(actual)}")

    host_needs = needs(blocks["host"])
    expected_host_needs = {"plan"} | REQUIRED_GATES
    if host_needs != expected_host_needs:
        fail(
            f"host must directly need exactly all gates, generated needs are {sorted(host_needs)}"
        )
    if "needs.plan.result == 'success'" not in blocks["host"]:
        fail("host must require successful plan")
    if "needs.plan.outputs.publishing == 'true'" not in blocks["host"]:
        fail("host must restrict publication to real dispatch")
    for job in REQUIRED_GATES:
        if not host_gate_condition(blocks["host"], job):
            fail(f"host condition lost generated result check for {job}")

    # No custom gate may independently skip after plan/local success. This is
    # cargo-dist 0.32's supported composition boundary; arbitrary job if/needs
    # expressions are not available in metadata configuration.
    for job in ("build-global-artifacts", "custom-preflight", "custom-archive-smoke"):
        if has_job_if(blocks[job]):
            fail(f"{job} gained an independent if condition and can skip a required gate")
    local_block = blocks["build-local-artifacts"]
    if not has_job_if(local_block):
        fail("local matrix lost its generated conditional")
    if "artifacts_matrix.include != null" not in local_block:
        fail("local matrix conditional lost plan-matrix presence guard")
    if "needs.plan.outputs.publishing == 'true'" not in local_block:
        fail("local matrix conditional lost publishing guard")

    base = {
        "plan": "success",
        "publishing": "true",
        "build-local-artifacts": "success",
        "build-global-artifacts": "success",
        "custom-preflight": "success",
        "custom-archive-smoke": "success",
    }
    if not graph_allows_publish(base):
        fail("all-success release graph was rejected")

    # Every required gate failure must block host. These cases catch a future
    # generated condition that accidentally omits one dependency.
    for job in REQUIRED_GATES:
        failed = dict(base)
        failed[job] = "failure"
        assert_negative(failed, f"failed {job}")

    # A skipped gate is never accepted by graph proof. In particular, this
    # catches the original preflight-failure cascade where local/global/smoke
    # were skipped and host's skip-tolerant expression published anyway.
    for job in REQUIRED_GATES:
        skipped = dict(base)
        skipped[job] = "skipped"
        assert_negative(skipped, f"skipped {job}")
    cascade = dict(base)
    for job in REQUIRED_GATES:
        cascade[job] = "skipped"
    assert_negative(cascade, "all required gates skipped")

    print(
        "cargo-dist 0.32 release gates ok: "
        "global hooks unconditional, host depends on preflight/local/global/smoke, "
        "failure and skipped paths blocked"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
